### ISSUE TITLE
Constantly fetching new data?

### ISSUE THREAD

**Issue by firasm** [ubco-mds-2020-labs/covid_vaccine_dashboard#10]
Hey team, just wanted to remind you that this dashboard is still running and still fetching data - perhaps too frequently? Consider reducing the frequency (especially if the dashboard is dormant) with which the data is pulled as it does take some compute cycles to do this.

**Comment by ericphillips99** [comment]
@firasm Thank you for pointing this out! I turned off the cron job. Hope you are doing well!
